[config]
# models
model="gpt-4-turbo-2024-04-09"
model_turbo="gpt-4o-2024-08-06"
fallback_models=["gpt-4o-2024-05-13"]

# CLI settings
git_provider="github"
publish_output=true
publish_output_progress=true
publish_output_no_suggestions=true
verbosity_level=0 # 0=minimal, 1=normal, 2=verbose
use_extra_bad_extensions=false

# Settings file configurations
use_wiki_settings_file=true
use_repo_settings_file=true
use_global_settings_file=true
ai_timeout=120 # Timeout in seconds for AI requests
skip_keys=[]

# Token limits
max_description_tokens=500
max_commits_tokens=500
max_model_tokens=32000 # Global token limit for all models
custom_model_max_tokens=-1 # For non-default models (-1 = no limit)

# Patch and context settings
patch_extension_skip_types=[".md", ".txt"]
allow_dynamic_context=true
max_extra_lines_before_dynamic_context=8 # Lines before hunk for function/class context
patch_extra_lines_before=3 # Additional lines before hunk (+3 default)
patch_extra_lines_after=1 # Additional lines after hunk (+3 default)

# General settings
secret_provider=""
cli_mode=false
ai_disclaimer_title="" # Pro: Title for collapsible AI disclaimer
ai_disclaimer="" # Pro: Full AI disclaimer text
output_relevant_configurations=false
large_patch_policy="clip" # Options: "clip", "skip"

# AI generation settings
seed=-1 # Positive value fixes seed (requires temperature=0)
temperature=0.2

# PR ignore patterns
ignore_pr_title=["^\\[Auto\\]", "^Auto"] # Regex patterns for PR titles to ignore
ignore_pr_target_branches=[] # Regex patterns for target branches to ignore
ignore_pr_source_branches=[] # Regex patterns for source branches to ignore
ignore_pr_labels=[] # PR labels to ignore

# Automation settings
is_auto_command=false # Auto-set for automation triggers
enable_ai_metadata=false # Enable AI metadata in outputs

[pr_reviewer] # /review command settings
# Feature toggles
require_score_review=false
require_tests_review=true
require_estimate_effort_to_review=true
require_can_be_split_review=false
require_security_review=true
require_ticket_analysis_review=true

# Review options
num_code_suggestions=0
inline_code_comments=false
ask_and_reflect=false
persistent_comment=true
extra_instructions=""
final_update_message=true

# Review labels
enable_review_labels_security=true
enable_review_labels_effort=true

# Incremental review settings
require_all_thresholds_for_incremental_review=false
minimal_commits_for_incremental_review=0
minimal_minutes_for_incremental_review=0
enable_intro_text=true
enable_help_text=false

# Auto approval
enable_auto_approval=false
maximal_review_effort=5

[pr_description] # /describe command settings
publish_labels=false
add_original_user_description=true
generate_ai_title=false
use_bullet_points=true
extra_instructions=""
enable_pr_type=true
final_update_message=true
enable_help_text=false
enable_help_comment=true

# Comment settings
publish_description_as_comment=false
publish_description_as_comment_persistent=true

# Changes walkthrough
enable_semantic_files_types=true
collapsible_file_list='adaptive' # true, false, 'adaptive'
inline_file_summary=false # false, true, 'table'

# Formatting
use_description_markers=false
include_generated_by_header=true

# Large PR handling
enable_large_pr_handling=true
max_ai_calls=4
async_ai_calls=true
mention_extra_files=true

[pr_questions] # /ask command settings
enable_help_text=false

[pr_code_suggestions] # /improve command settings
max_context_tokens=16000
commitable_code_suggestions=false
dual_publishing_score_threshold=-1 # -1=disabled, 0-10=threshold
focus_only_on_problems=false
extra_instructions=""
rank_suggestions=false
enable_help_text=false
enable_chat_text=false
enable_intro_text=true
persistent_comment=true
max_history_len=4

# Pro: Apply suggestions
apply_suggestions_checkbox=true

# Suggestion scoring
suggestions_score_threshold=0 # 0-10 (recommend max 8)

# Extended mode settings
auto_extended_mode=true
num_code_suggestions_per_chunk=4
max_number_of_calls=3
parallel_calls=true
rank_extended_suggestions=false
final_clip_factor=0.8

# Self-review settings
demand_code_suggestions_self_review=false
code_suggestions_self_review_text="**Author self-review**: I have reviewed the PR code suggestions, and addressed the relevant ones."
approve_pr_on_self_review=false # Pro feature
fold_suggestions_on_self_review=true # Pro feature

# Pro: Suggestion impact
publish_post_process_suggestion_impact=true
wiki_page_accepted_suggestions=true

[pr_custom_prompt] # /custom_prompt command settings
prompt="""\
The code suggestions should focus only on the following:
- ...
- ...
...
"""
suggestions_score_threshold=0
num_code_suggestions_per_chunk=4
self_reflect_on_custom_suggestions=true
enable_help_text=false

[pr_add_docs] # /add_docs command settings
extra_instructions=""
docs_style="Sphinx" # Supported styles: Google, Numpy, Sphinx, PEP257, reStructuredText
file="" # Optional: Specify file for multiple components
class_name="" # Optional: Specify class for multiple methods

[pr_update_changelog] # /update_changelog command settings
push_changelog_changes=false
extra_instructions=""

[pr_analyze] # /analyze command settings
enable_help_text=true

[pr_test] # /test command settings
extra_instructions=""
testing_framework="" # Specify testing framework
num_tests=3 # Max 5 tests
avoid_mocks=true
file="" # Optional: Specify file
class_name="" # Optional: Specify class

[pr_improve_component] # /improve_component command settings
num_code_suggestions=4
extra_instructions=""
file="" # Optional: Specify file
class_name="" # Optional: Specify class

[checks] # Pro: /checks command settings
enable_auto_checks_feedback=true
excluded_checks_list=["lint"]
persistent_comment=true
enable_help_text=true
final_update_message=false

[pr_help] # /help command settings
force_local_db=false
num_retrieved_snippets=5

[pr_config] # /config command settings

[github]
deployment_type="user" # "app" or "user"
ratelimit_retries=5
base_url="https://api.github.com"
publish_inline_comments_fallback_with_verification=true
try_fix_invalid_inline_comments=true
app_name="pr-insight"
ignore_bot_pr=true

[github_action_config]
# Set in .github/workflows/pr-insight.yaml:
# auto_review=true
# auto_describe=true
# auto_improve=true
# pr_actions=['opened', 'reopened', 'ready_for_review', 'review_requested']

[github_app]
bot_user="github-actions[bot]"
override_deployment_type=true

# Pull request event settings
handle_pr_actions=['opened', 'reopened', 'ready_for_review']
pr_commands=[
    "/describe --pr_description.final_update_message=false",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve",
]

# Push event settings
handle_push_trigger=false
push_trigger_ignore_bot_commits=true
push_trigger_ignore_merge_commits=true
push_trigger_wait_for_initial_review=true
push_trigger_pending_tasks_backlog=true
push_trigger_pending_tasks_ttl=300
push_commands=[
    "/describe",
    "/review --pr_reviewer.num_code_suggestions=0",
]

[gitlab]
url="https://gitlab.com"
pr_commands=[
    "/describe --pr_description.final_update_message=false",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve",
]
handle_push_trigger=false
push_commands=[
    "/describe",
    "/review --pr_reviewer.num_code_suggestions=0",
]

[bitbucket_app]
pr_commands=[
    "/describe --pr_description.final_update_message=false",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve --pr_code_suggestions.commitable_code_suggestions=true --pr_code_suggestions.suggestions_score_threshold=7",
]
avoid_full_files=false

[local]
# Optional custom paths:
# description_path="path/to/description.md"
# review_path="path/to/review.md"

[gerrit]
# Required settings:
# url="ssh://gerrit.example.com:29418"
# user="ai-reviewer"
# patch_server_endpoint="http://127.0.0.1:5000/patch"
# patch_server_token=""

[bitbucket_server]
url="" # Example: "https://git.bitbucket.com"
pr_commands=[
    "/describe --pr_description.final_update_message=false",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve --pr_code_suggestions.commitable_code_suggestions=true --pr_code_suggestions.suggestions_score_threshold=7",
]

[litellm]
enable_callbacks=false
success_callback=[]
failure_callback=[]
service_callback=[]

[pr_similar_issue]
skip_comments=false
force_update_dataset=false
max_issues_to_scan=500
vectordb="pinecone"

[pr_find_similar_component]
class_name=""
file=""
search_from_org=false
allow_fallback_less_words=true
number_of_keywords=5
number_of_results=5

[pinecone]
# Configure in .secrets.toml:
# api_key=...
# environment="gcp-starter"

[lancedb]
uri="./lancedb"

[best_practices]
content=""
max_lines_allowed=800
enable_global_best_practices=false
