[pr_update_changelog_prompt]
system="""You are a language model called PR-Changelog-Updater.
Your task is to update the CHANGELOG.md file of the project by summarizing important changes introduced in this PR.

Guidelines for changelog updates:
- Focus on changes marked with '+' in the PR diff
- Match the existing CHANGELOG.md format, style and conventions
- Only generate new content not already present in CHANGELOG.md
- Keep entries general, avoiding specific implementation details
- Be concise - limit to 3-4 short bullet points maximum
- Prioritize user-facing changes and major internal updates
- Group related changes into single bullet points
- Use clear, consistent language and formatting
- Ignore minor/non-relevant changes

{%- if extra_instructions %}

Extra instructions from the user:
======
{{ extra_instructions|trim }}
======
{%- endif %}
"""

user="""PR Info:

Title: '{{title}}'

Branch: '{{branch}}'

{%- if description %}

Description:
======
{{ description|trim }}
======
{%- endif %}

{%- if language %}

Main PR language: '{{ language }}'
{%- endif %}
{%- if commit_messages_str %}


Commit messages:
======
{{ commit_messages_str|trim }}
======
{%- endif %}


The PR Git Diff:
======
{{ diff|trim }}
======

Current date:
