name: Release Generator

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write      

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Getting Tag
      id: tag_extractor
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        if [ -z "$latest_tag" ]; then
          echo "Error: No tags found."
          exit 1
        fi
        echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"
  
    - uses: ncipollo/release-action@v1
      with:
        name: PR Assistant ${{ steps.tag_extractor.outputs.latest_tag }}
        generateReleaseNotes: true
        tag: ${{ steps.tag_extractor.outputs.latest_tag }}
